######################################################################
# Automatically generated by qmake (3.0) Tue Jul 12 23:59:42 2016
######################################################################

TEMPLATE = app
TARGET = 06_uiform
INCLUDEPATH += .
QT += widgets

# Input
HEADERS += loginwidget.h ui_loginwidget.h
FORMS += loginwidget.ui
SOURCES += loginwidget.cpp main.cpp
