######################################################################
# Automatically generated by qmake (3.0) Tue Jul 12 01:11:50 2016
######################################################################

TEMPLATE = app
TARGET = 04_subclassing
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += mydialog.h
SOURCES += main.cpp mydialog.cpp
