######################################################################
# Automatically generated by qmake (3.0) Sat Jul 9 01:09:13 2016
######################################################################

TEMPLATE = app
TARGET = 00_skeleton
INCLUDEPATH += .

CONFIG -= app_bundle
CONFIG += console

# Input
SOURCES += main.cpp
