######################################################################
# Automatically generated by qmake (3.0) Mon Jul 11 00:57:17 2016
######################################################################

TEMPLATE = app
TARGET = 03_signalslot_ext
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
