######################################################################
# Automatically generated by qmake (3.0) Sun Jul 10 23:11:26 2016
######################################################################

TEMPLATE = app
TARGET = 02_signalslot
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
