######################################################################
# Automatically generated by qmake (3.0) Tue Jul 12 22:05:22 2016
######################################################################

TEMPLATE = app
TARGET = 05_leakcheck
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += mydialog.h \
    mywidget.h
SOURCES += main.cpp mydialog.cpp \
    mywidget.cpp
