######################################################################
# Automatically generated by qmake (3.0) Sat Jul 9 02:24:50 2016
######################################################################

TEMPLATE = app
TARGET = 01_widget
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += main.cpp
